M48
; DRILL file {KiCad (6.0.0)} date Tue Jun 21 21:02:01 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-21T21:02:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X100.33Y-121.92
X100.33Y-132.08
T2
X81.28Y-63.5
X81.28Y-139.7
X210.82Y-63.5
X210.82Y-139.7
T3
X100.33Y-127.0
T0
M30
